Components/TypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using mission09_bshorne.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission09_bshorne.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private ILibraryRepository repo { get; set; }

        public TypesViewComponent (ILibraryRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["bookType"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

Views/Shared/BookSummary.cshtml
@{
}
@model Book
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h3>
            @Model.Title
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h3>
    </div>
    <form method="post" asp-page="/Shop">

        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-right">Add to Cart</button>
        </span>
        <!--Bootstrap 2/2 having a reaccuring IMG with Style applied-->
        <img height="200" style="outline-style:solid; outline-width:thin; outline-color:black;" src="~/unnamed.png" />
    </form>
</div>
<ul>
    <li>Author: @Model.Author</li>
    <li>Publisher: @Model.Publisher</li>
    <li>Isbn: @Model.Isbn</li>
    <li>Classification: @Model.Classification</li>
    <li>Category: @Model.Category</li>
    <li>Number of Pages: @Model.PageCount</li>
</ul>

<br />

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-grid.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha512-ZYg+hQvLlM0W9C3P6vTpes5LmJ66G2EsroxDNzwD6qiulckldb29eD9I672HL2X+LH5nRhY1sQqZLJGB+aUUPg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">BOOK STORE</span>
        <div class="col-6 text-right">
            <vc:cart-summary />
        </div>
    </div>
    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:types></vc:types>
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>